# Generated by Django 2.1.1 on 2021-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_second',
            fields=[
                ('first', models.CharField(max_length=255)),
                ('second', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'first_second',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
