# Generated by Django 2.1.1 on 2021-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210328_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='second_third',
            fields=[
                ('second', models.CharField(max_length=255)),
                ('third', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'second_third',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='third_fourth',
            fields=[
                ('third', models.CharField(max_length=255)),
                ('fourth', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'third_fourth',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='first_second',
            options={'managed': True},
        ),
    ]
