# Generated by Django 2.1.1 on 2021-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210328_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourth_fimname',
            fields=[
                ('security_id', models.CharField(blank=True, max_length=255, null=True)),
                ('firmname', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fourth', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fourth_firmname',
                'managed': False,
            },
        ),
    ]
