# Generated by Django 2.1.1 on 2021-04-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_fourth_fimname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fourth_fimname',
            options={'managed': True},
        ),
    ]
