# Generated by Django 2.1.1 on 2021-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210403_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fourth_fimname',
            new_name='fourth_firmname',
        ),
    ]
