# Generated by Django 2.1.1 on 2021-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210403_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='enterprise_sentiment',
            fields=[
                ('click_num', models.IntegerField(blank=True, null=True)),
                ('review_num', models.CharField(blank=True, max_length=225, null=True)),
                ('opinion', models.CharField(max_length=255)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('stock_id', models.CharField(max_length=255)),
                ('vocabulary1', models.CharField(blank=True, max_length=255, null=True)),
                ('vocabulary2', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_sentiment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enterprise_sentiment',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='enterprise_sentiment',
            unique_together={('date', 'stock_id', 'opinion')},
        ),
    ]
