# Generated by Django 2.1.1 on 2021-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20210404_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_sentiment',
            name='date',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
