# Generated by Django 2.1.1 on 2021-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20210423_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
