# Generated by Django 2.1.1 on 2021-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_user_info_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img_src',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
