# Generated by Django 2.1.1 on 2021-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20210423_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img_src',
            field=models.CharField(max_length=255),
        ),
    ]
